spring:
  datasource:
    url: jdbc:postgresql://${ITX_POSTGRES_HOST}:${ITX_POSTGRES_PORT}/${ITX_POSTGRES_DB_NAME}
    username: ${ITX_POSTGRES_USER}
    password: ${ITX_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
