# the include should be done only once, at the beginning of the custom configuration file
include classpath("application.conf")

queues {
  test-itx-control-standard {
    defaultVisibilityTimeout = 30 seconds
    deadLettersQueue {
      name = "test-itx-control-standard-dlq"
      maxReceiveCount = 1
    }
  }
  test-itx-control-premium {
    defaultVisibilityTimeout = 30 seconds
    deadLettersQueue {
      name = "test-itx-control-premium-dlq"
      maxReceiveCount = 1
    }
  }
  test-itx-compute-standard {
    defaultVisibilityTimeout = 30 seconds
    deadLettersQueue {
      name = "test-itx-compute-standard-dlq"
      maxReceiveCount = 1
    }
  }
  test-itx-compute-premium {
    defaultVisibilityTimeout = 30 seconds
    deadLettersQueue {
      name = "test-itx-compute-premium-dlq"
      maxReceiveCount = 1
    }
  }
  test-itx-control-standard-dlq {}
  test-itx-control-premium-dlq {}
  test-itx-compute-standard-dlq {}
  test-itx-compute-premium-dlq {}
}
